Recipe.create(title: 'Black Bean Potato and Onion Tacos')
Ingredient.create(name: 'Garlic black beans')
Recipe.create(title: 'Thanksgiving Tacos')
Ingredient.create(name: 'Salsa de aguacate')
Ingredient.create(name: 'Deezthugs smokey turkey tacos')
Recipe.create(title: 'Tempeh reuben tacos ')
Ingredient.create(name: 'Pepper tempeh')
Recipe.create(title: 'Thanksgiving Tacos')
Ingredient.create(name: 'Fresh corn tortillas')
Ingredient.create(name: 'Salsa de aguacate')
Ingredient.create(name: 'Deezthugs smokey turkey tacos')
Recipe.create(title: 'Vegan Red Cabbage Tacos')
Ingredient.create(name: 'Garlic black beans')
Recipe.create(title: 'Steak Sweet Potato and Apple Tacos')
Ingredient.create(name: 'Chopped steak')
Recipe.create(title: 'Morrocan Lamb Tacos')
Ingredient.create(name: 'Moroccan lamb')
Recipe.create(title: 'Chorizo Sweet Potato and Apple Tacos with Chipotle Sauce')
Ingredient.create(name: 'Chipotle sauce')
Ingredient.create(name: 'Chorizo')
Recipe.create(title: 'Chicken Verde Corn and Black Bean Tacos with Pico de Gallo and Salsa de Aguacate')
Ingredient.create(name: 'Salsa de aguacate')
Ingredient.create(name: 'Corn and black beans')
Recipe.create(title: 'Vegan Red Cabbage Tacos')
Ingredient.create(name: 'Garlic black beans')
Recipe.create(title: 'Chorizo Sweet Potato and Apple Tacos with Chipotle Sauce')
Ingredient.create(name: 'Chipotle sauce')
Ingredient.create(name: 'Chorizo')
Recipe.create(title: 'Pulled Pork Chard and Pickled Onion Tacos')
Ingredient.create(name: 'Pickled red onions')
Ingredient.create(name: 'Swiss chard')
Recipe.create(title: 'Traditional American Taco')
Ingredient.create(name: 'Hard corn shells traditional us')
Ingredient.create(name: 'Black olives')
Ingredient.create(name: 'Ground beef traditional us')
Recipe.create(title: 'Slow Cooker Chicken in Chile de Arbol sauce')
Ingredient.create(name: 'Salsa de aguacate')
Ingredient.create(name: 'Slow cooked salsa verde chicken')
Recipe.create(title: 'Asian Style Tacos')
Ingredient.create(name: 'Asian cabbage slaw')
Ingredient.create(name: 'Asian style tofu or pork marinade')
Recipe.create(title: 'Steak Sweet Potato and Apple Tacos')
Ingredient.create(name: 'Chopped steak')
Recipe.create(title: 'Fish Tacos')
Ingredient.create(name: 'Chipotle sauce')
Ingredient.create(name: 'Baked tilapia')
Recipe.create(title: 'Swiss Chard Tacos')
Ingredient.create(name: 'Swiss chard')
Recipe.create(title: 'Zucchini and Corn Tacos')
Ingredient.create(name: 'Simple salsa verde')
Ingredient.create(name: 'Zucchini and corn filling')
Recipe.create(title: 'Thanksgiving Tacos')
Ingredient.create(name: 'Salsa de aguacate')
Ingredient.create(name: 'Deezthugs smokey turkey tacos')
Recipe.create(title: 'Fish Tacos')
Ingredient.create(name: 'Chipotle sauce')
Ingredient.create(name: 'Baked tilapia')
Recipe.create(title: 'Slow Cooker Chicken in Chile de Arbol sauce')
Ingredient.create(name: 'Salsa de aguacate')
Ingredient.create(name: 'Slow cooked salsa verde chicken')
Recipe.create(title: 'Traditional American Taco')
Ingredient.create(name: 'Hard corn shells traditional us')
Ingredient.create(name: 'Black olives')
Ingredient.create(name: 'Ground beef traditional us')
Recipe.create(title: 'Traditional American Taco')
Ingredient.create(name: 'Hard corn shells traditional us')
Ingredient.create(name: 'Black olives')
Ingredient.create(name: 'Ground beef traditional us')
Recipe.create(title: 'Black Bean Potato and Onion Tacos')
Ingredient.create(name: 'Garlic black beans')
Recipe.create(title: 'Chicken Verde Corn and Black Bean Tacos with Pico de Gallo and Salsa de Aguacate')
Ingredient.create(name: 'Salsa de aguacate')
Ingredient.create(name: 'Corn and black beans')
Recipe.create(title: 'Tacos de Carnitas')
Ingredient.create(name: 'Onions and cilantro')
Ingredient.create(name: 'Fat poached carnitas')
Recipe.create(title: 'Black Bean Potato and Onion Tacos')
Ingredient.create(name: 'Garlic black beans')
Recipe.create(title: 'Zucchini and Corn Tacos')
Ingredient.create(name: 'Simple salsa verde')
Ingredient.create(name: 'Zucchini and corn filling')
Recipe.create(title: 'Chicken Verde Corn and Black Bean Tacos with Pico de Gallo and Salsa de Aguacate')
Ingredient.create(name: 'Salsa de aguacate')
Ingredient.create(name: 'Corn and black beans')
Recipe.create(title: 'Steak Sweet Potato and Apple Tacos')
Ingredient.create(name: 'Chopped steak')
Recipe.create(title: 'Tempeh reuben tacos ')
Ingredient.create(name: 'Pepper tempeh')
Recipe.create(title: 'Tempeh reuben tacos ')
Ingredient.create(name: 'Pepper tempeh')
Recipe.create(title: 'Slow Cooker Chicken in Chile de Arbol sauce')
Ingredient.create(name: 'Salsa de aguacate')
Ingredient.create(name: 'Slow cooked salsa verde chicken')
Recipe.create(title: 'Chorizo Sweet Potato and Apple Tacos with Chipotle Sauce')
Ingredient.create(name: 'Chipotle sauce')
Ingredient.create(name: 'Chorizo')
Recipe.create(title: 'Traditional American Taco')
Ingredient.create(name: 'Hard corn shells traditional us')
Ingredient.create(name: 'Black olives')
Ingredient.create(name: 'Ground beef traditional us')
Recipe.create(title: 'Spaghetti Squash Tacos')
Ingredient.create(name: 'Above average tomato sauce')
Ingredient.create(name: 'Spaghetti squash')
Recipe.create(title: 'Pulled Pork Chard and Pickled Onion Tacos')
Ingredient.create(name: 'Pickled red onions')
Ingredient.create(name: 'Swiss chard')
Recipe.create(title: 'Zucchini and Corn Tacos')
Ingredient.create(name: 'Simple salsa verde')
Ingredient.create(name: 'Zucchini and corn filling')
Recipe.create(title: 'Traditional American Taco')
Ingredient.create(name: 'Hard corn shells traditional us')
Ingredient.create(name: 'Black olives')
Ingredient.create(name: 'Ground beef traditional us')
Recipe.create(title: 'Spaghetti Squash Tacos')
Ingredient.create(name: 'Above average tomato sauce')
Ingredient.create(name: 'Spaghetti squash')
Recipe.create(title: 'Slow Cooker Chicken in Chile de Arbol sauce')
Ingredient.create(name: 'Salsa de aguacate')
Ingredient.create(name: 'Slow cooked salsa verde chicken')
Recipe.create(title: 'Chicken Verde Corn and Black Bean Tacos with Pico de Gallo and Salsa de Aguacate')
Ingredient.create(name: 'Salsa de aguacate')
Ingredient.create(name: 'Slow cooked salsa verde chicken')
Recipe.create(title: 'Traditional American Taco')
Ingredient.create(name: 'Hard corn shells traditional us')
Ingredient.create(name: 'Black olives')
Ingredient.create(name: 'Ground beef traditional us')
Recipe.create(title: 'Baja Fish Tacos')
Ingredient.create(name: 'Baja white sauce')
Ingredient.create(name: 'Baja beer battered fish')
Recipe.create(title: 'Slow Cooker Chicken in Chile de Arbol sauce')
Ingredient.create(name: 'Salsa de aguacate')
Ingredient.create(name: 'Slow cooked salsa verde chicken')
Recipe.create(title: 'Black Bean Potato and Onion Tacos')
Ingredient.create(name: 'Garlic black beans')
Recipe.create(title: 'Steak Sweet Potato and Apple Tacos')
Ingredient.create(name: 'Chopped steak')
Recipe.create(title: 'Morrocan Lamb Tacos')
Ingredient.create(name: 'Moroccan lamb')
Recipe.create(title: 'Fish Tacos')
Ingredient.create(name: 'Chipotle sauce')
Ingredient.create(name: 'Baked tilapia')
